---
resource_types:
  - name: pushgateway
    type: docker-image
    source:
      repository: michaellihs/prometheus-pushgateway-resource
      tag: dev-6

resources:
  - name: pushgateway
    type: pushgateway
    source:
      url: http://pushgw:9091
      job: concourse-pushgw-development

jobs:
  - name: pushgw-metric
    plan:
      - task: task1
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: busybox}
          run:
            path: echo
            args:
              - hello world
        on_success:
          put: pushgateway
          params:
            metric: successful_metric{label="label-content"}
            job: task1
            value: 13
      - task: task2
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: busybox}
          run:
            path: echo
            args:
              - hello world
        on_success:
          put: pushgateway
          params:
            metric: successful_metric
            job: task2
            value: 1
            labels:
              label_1: value_1
              label_2: value_2

      - task: task3
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: busybox}
          run:
            path: echo
            args:
              - hello world
        on_success:
          put: pushgateway
          params:
            metric: successful_metric
            job: task2
            value: 14
            labels:
              BUILD_ID: $BUILD_ID
              BUILD_NAME: $BUILD_NAME

